server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

# The default thread pool can grow up to 200 threads and has 10 worker threads
spring:
  application:
    name: catalog-service
